spring:
  application:
    name: functions
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max

custom:
  weather:
    api-key: ${GAODE_WEATHER_API_KEY}
    api-url: https://restapi.amap.com/v3/weather
